### ISSUE TITLE
Moscow niet compleet

### ISSUE THREAD

**Issue by tkleinman** [Mustache2605/SoundSharp#1]
In de informatiebehoefte is de moscow nog niet volledig. Zo zie ik geen functionaliteit omtrent de statistische gegevens en de beschrijving van een externe opslag en gui.

**Comment by Mustache2605** [comment]
Aangepast en opnieuw geüpload!

**Comment by tkleinman** [comment]
Nog steeds mis ik functionaliteiten

**Comment by Mustache2605** [comment]
welke functionaliteiten............... lolz

**Comment by Mustache2605** [comment]
Nu echt goed aangepast, meer kan ik er niet uithalen. Opgelost hoop ik :D
