### ISSUE TITLE
Strokenplanning 

### ISSUE THREAD

**Issue by tkleinman** [Mustache2605/SoundSharp#2]
Strokenplanning is niet op orde, je hebt bijvoorbeeld het TO (technisch ontwerp) gepland, die maken wij deze cyclus niet. Verder mis ik de Informatiebehoefte en Plan van aanpak in de planning. In het PVA heb je het over projectactiviteiten, die zou ik graag terug willen zien in deze planning.

**Comment by Mustache2605** [comment]
Strokenplanning aangepast en opnieuw geüpload.
